<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
</head>
<body>

<?php echo $content ?>

<style>
#backButton {
    position: fixed;
    top: 8px;
    right: 8px;

    border: 1px solid #8f8f8f;
    border-radius: 3px;
    font-size: 20px;
    padding: 8px;

    text-decoration: none;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #000000;
    background-color: #FFF8F0;


}
#searchInput {
    border: 1px solid #8f8f8f;
    border-radius: 3px;
    font-size: 20px;
    padding: 8px;
    width: 400px;
}

#searchSubmitButton {
    border: 1px solid #8f8f8f;
    border-radius: 3px;
    font-size: 20px;
    padding: 8px;
}
#itemsList>p {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 16px;
    padding: 8px;
    margin: 0;
}

#itemsList>p:hover {
    background-color: #FFF8F0;
}

#loadMoreButton {
    border: 1px solid #8f8f8f;
    border-radius: 3px;
    font-size: 16px;
    padding: 8px;
    background-color: #FFF8F0;
    margin: 8px;
    display: none;

}
#noMoreMessage {
    display: none;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
</style>
</body>